Repository mohamed-souiyeh/transandance, pull requests merged in 2024-02, with the labels that each got.

#126 progress circle and search backgound
  front-end/src/pages/components/ProgressCercle.tsx
  front-end/src/pages/components/UserInfo.tsx
  front-end/src/pages/components/bubble.tsx
  front-end/src/pages/components/groupsIcons.tsx
  front-end/src/pages/search.tsx
Labels: enhancement, bugFix, simple progress

#128 Front
  back-end/src/database/users/users.service.ts
  front-end/src/App.tsx
  front-end/src/pages/chat.tsx
  front-end/src/pages/components/Acheivements.tsx
  front-end/src/pages/components/GameHistory.tsx
  front-end/src/pages/components/ProgressCercle.tsx
  front-end/src/pages/components/UserInfo.tsx
  front-end/src/pages/components/addFriendsPopup.tsx
  front-end/src/pages/components/blocked.tsx
  front-end/src/pages/components/bubble.tsx
  front-end/src/pages/components/channels.tsx
  front-end/src/pages/components/contacts.tsx
  front-end/src/pages/components/friends.tsx
  front-end/src/pages/components/groupMembers.tsx
  front-end/src/pages/components/groups.tsx
  front-end/src/pages/components/groupsIcons.tsx
  front-end/src/pages/components/history.tsx
  front-end/src/pages/components/icons.tsx
  front-end/src/pages/components/logout.tsx
  front-end/src/pages/components/menuDefault.tsx
  front-end/src/pages/components/messages.tsx
  front-end/src/pages/components/network.tsx
  front-end/src/pages/components/protectedRoomPopup.tsx
  front-end/src/pages/components/ranked.tsx
  front-end/src/pages/components/requests.tsx
  front-end/src/pages/components/requireAuth.tsx
  front-end/src/pages/components/rooms.tsx
  front-end/src/pages/components/twofa.tsx
  front-end/src/pages/home.tsx
  front-end/src/pages/loading.tsx
  front-end/src/pages/login.tsx
  front-end/src/pages/manageGoups.tsx
  front-end/src/pages/profile.tsx
  front-end/src/pages/search.tsx
  front-end/src/pages/twofaconfirm.tsx
  front-end/src/pages/twofactorauthpage.tsx
  front-end/src/pages/user.tsx
  front-end/src/pages/userSetup.tsx
Labels: enhancement, bugFix

#129 Game
  back-end/.gitignore
  back-end/avatars/2023_12_21_0yx_Kleki-898357.png
  back-end/avatars/2856-minecraft-anime-girl-3d0864.png
  back-end/avatars/2856-minecraft-anime-girl-71ce3c.png
  back-end/avatars/2856-minecraft-anime-girl-bbff5e.png
  back-end/avatars/2856-minecraft-anime-girl-cffcaf.png
  back-end/avatars/2959-minecraft-anime-boy-6bbff5.png
  back-end/avatars/2959-minecraft-anime-boy-d08641.png
  back-end/avatars/2959-minecraft-anime-boy-ffcaf7.png
  back-end/avatars/Screenshot from 2023-12-07 23-16-48-8744b6.png
  back-end/avatars/Screenshot from 2023-12-19 15-56-58-6b3fc2.png
  back-end/avatars/avatar-47385a.jpg
  back-end/avatars/avatar-7385ad.jpg
  back-end/avatars/bot-703d62.png
  back-end/avatars/bot-7dfcdb.png
  back-end/avatars/bot-dfcdbf.png
  back-end/avatars/bot-fcdbfc.png
  back-end/avatars/hh-319d5b.jpg
  back-end/avatars/hh-744b64.jpg
  back-end/avatars/hh-a319d5.jpg
  back-end/avatars/kratos-98f3d3.jpg
  back-end/avatars/kratos-998f3d.jpg
  back-end/avatars/kratos-c0da96.jpg
  back-end/avatars/veteran-6b4317.png
  back-end/src/auth/auth.service.ts
  back-end/src/auth/jwt/config/jwt.config.ts
  back-end/src/database/conversations/conversations.service.ts
  back-end/src/errors.interceptor.ts
  back-end/src/game/game.module.ts
  back-end/src/game/game.service.ts
  back-end/src/game/gamegateway.ts
  back-end/src/sockets/chat/chat.gateway.ts
  front-end/src/App.tsx
  front-end/src/clientSocket.tsx
  front-end/src/main.tsx
  front-end/src/pages/chat.tsx
  front-end/src/pages/components/bubble.tsx
  front-end/src/pages/components/groups.tsx
  front-end/src/pages/components/icons.tsx
  front-end/src/pages/components/messages.tsx
  front-end/src/pages/components/network.tsx
  front-end/src/pages/components/requests.tsx
  front-end/src/pages/components/rooms.tsx
  front-end/src/pages/components/twofa.tsx
  front-end/src/pages/game/botmode.tsx
  front-end/src/pages/game/game.tsx
  front-end/src/pages/loading.tsx
  front-end/src/pages/manageGoups.tsx
  front-end/src/pages/profile.tsx
  front-end/src/pages/setupSocket.ts
  front-end/src/pages/userSetup.tsx
Labels: bugFix

#132 score sure is number
  front-end/src/pages/components/ProgressCercle.tsx
Labels: bugFix

#133 Game
  back-end/src/auth/auth.service.ts
  back-end/src/auth/jwt/strategy/jwt-refresh.strategy.ts
  back-end/src/database/conversations/conversations.controller.ts
  back-end/src/database/conversations/conversations.service.ts
  back-end/src/database/notifications/notifications.service.ts
  back-end/src/database/users/users.controller.ts
  back-end/src/database/users/users.service.ts
  back-end/src/game/gamegateway.ts
  back-end/src/sockets/chat/chat.gateway.ts
  back-end/src/sockets/main-name-space/main-name-space.gateway.ts
  front-end/src/App.tsx
  front-end/src/main.tsx
  front-end/src/pages/components/UserInfo.tsx
  front-end/src/pages/components/blocked.tsx
  front-end/src/pages/components/contacts.tsx
  front-end/src/pages/components/friends.tsx
  front-end/src/pages/components/logout.tsx
  front-end/src/pages/components/messages.tsx
  front-end/src/pages/manageGoups.tsx
  front-end/src/pages/profile.tsx
  front-end/src/pages/search.tsx
  front-end/src/pages/userSetup.tsx
Labels: bugFix

#135 Game
  Makefile
  back-end/package.json
  back-end/src/auth/auth.service.ts
  back-end/src/auth/jwt/config/jwt.config.ts
  back-end/src/database/conversations/conversations.controller.ts
  back-end/src/database/conversations/conversations.module.ts
  back-end/src/sockets/chat/channel/channel.guard.ts
  back-end/src/sockets/chat/chat.gateway.ts
  back-end/src/sockets/chat/get-all-msgs/get-all-msgs.guard.ts
  front-end/package.json
Labels: bugFix

#136 fixed some bugs
  back-end/src/database/conversations/conversations.service.ts
  back-end/src/sockets/main-name-space/main-name-space.gateway.ts
  front-end/src/App.tsx
  front-end/src/pages/chat.tsx
  front-end/src/pages/components/contacts.tsx
  front-end/src/pages/components/messages.tsx
  front-end/src/pages/components/rooms.tsx
  front-end/src/pages/manageGoups.tsx
Labels: bugFix
